import * as path from "path";
import assert from "assert";
const tester = require("circom_tester").wasm;
import { getSignal } from "./utils";

// ffjavascript has no types so leave circuit with untyped
type CircuitT = any;

// One-shot Poseidon2 reference vectors in the compression layout of the Logos ecosystem
// (state [inputs.., 0] -> state[0], capacity zero last, HorizenLabs constant set).
// Sources: the arity-2 vectors over (0,0), (1,0), (0,1), (1,1) are the official Nomos
// compression-mode test vectors of the "Common Cryptographic Components" specification,
// pinned as the big-endian hex the spec prints; every other vector was generated by
// running the hash functions of the Logos reference implementation
// https://github.com/logos-storage/rust-poseidon-bn254-pure over the same inputs.
// The same values are pinned by the zerokit Rust tests.
const vectors: { arity: number; inputs: bigint[]; expected: bigint }[] = [
  {
    arity: 1,
    inputs: [1n],
    expected:
      4220003009428892662276135118827607177546592752204629865937061707152838643028n,
  },
  {
    arity: 2,
    inputs: [0n, 0n],
    expected:
      0x2ed1da00b14d635bd35b88ab49390d5c13c90da7e9e3a5f1ea69cd87a0aa3e82n,
  },
  {
    arity: 2,
    inputs: [1n, 0n],
    expected:
      0x063c4e8cac9a858304f0035b069255b069288c2af698ececf362cd8ec8c96665n,
  },
  {
    arity: 2,
    inputs: [0n, 1n],
    expected:
      0x222816f2669279d4c256ed2f196e8b0d54df83d35d61811bac36ea4e858483fcn,
  },
  {
    arity: 2,
    inputs: [1n, 1n],
    expected:
      0x277530b5f2b87dfe4535f43bb1998eda77736b4b05d15d983503566743c88031n,
  },
  {
    arity: 2,
    inputs: [1n, 2n],
    expected:
      19440202363237281411582519622441422429699333916864112080167601237210978582482n,
  },
  {
    arity: 2,
    inputs: [3n, 4n],
    expected:
      6841465511530398863060979759285255211138061951621999722672958394106152792555n,
  },
  {
    arity: 2,
    inputs: [123456789n, 987654321n],
    expected:
      9009407154000298779772606758330192725127596677845856717883134607702775218298n,
  },
  {
    arity: 3,
    inputs: [1n, 2n, 3n],
    expected:
      17987529774510619908913366712228014240324707442444135579896039517815896575124n,
  },
];

// Field-boundary vectors (every input = p - 1), computed with the hash functions of
// rust-poseidon-bn254-pure and matched by zerokit's Poseidon2 implementation.
const P_MINUS_1 =
  21888242871839275222246405745257275088548364400416034343698204186575808495616n;
const boundaryVectors: { arity: number; inputs: bigint[]; expected: bigint }[] =
  [
    {
      arity: 1,
      inputs: [P_MINUS_1],
      expected:
        9294971039725959602331275756280672770500152342309238745956501791342167982753n,
    },
    {
      arity: 2,
      inputs: [P_MINUS_1, P_MINUS_1],
      expected:
        4117823475917035838497081381939932928454443816554499594232502410326101827821n,
    },
    {
      arity: 3,
      inputs: [P_MINUS_1, P_MINUS_1, P_MINUS_1],
      expected:
        4433769735955410370525159795790712404476733300548172692666348652860643522637n,
    },
  ];

describe("Test poseidon2.circom", function () {
  this.timeout(60000);

  const circuits: { [arity: number]: CircuitT } = {};

  before(async function () {
    for (const arity of [1, 2, 3]) {
      const circuitPath = path.join(
        __dirname,
        "circuits",
        `poseidon2_arity${arity}.circom`,
      );
      circuits[arity] = await tester(circuitPath);
    }
  });

  it("Should match the Poseidon2 reference vectors for every arity", async () => {
    for (const { arity, inputs, expected } of vectors) {
      const circuit = circuits[arity];
      const witness = await circuit.calculateWitness({ inputs }, true);
      await circuit.checkConstraints(witness);
      const out = await getSignal(circuit, witness, "out");
      assert.equal(
        out,
        expected,
        `Poseidon2 mismatch for arity ${arity} inputs [${inputs}]`,
      );
    }
  });

  it("Should match the native Poseidon2 at the field boundary (p - 1 inputs)", async () => {
    for (const { arity, inputs, expected } of boundaryVectors) {
      const circuit = circuits[arity];
      const witness = await circuit.calculateWitness({ inputs }, true);
      await circuit.checkConstraints(witness);
      const out = await getSignal(circuit, witness, "out");
      assert.equal(
        out,
        expected,
        `Poseidon2 mismatch for arity ${arity} at the field boundary`,
      );
    }
  });
});
